### PR TITLE
Add a rzSliderShowTicks

### PR DESCRIPTION
**Pull request by ValentinH**
```js
<rzslider rz-slider-model="priceSlider" rz-slider-show-ticks="true"></rzslider>
```

It displays a tick for each possible value. See the Example on the demo page or on [this fiddle](http://jsfiddle.net/ngrq2kdm/).

### CODE REVIEW

**Comment by soee** [comment]
I'm not using it atm. but it is a nice feature, so: +1

**Comment by adgoncal** [comment]
It is a good idea, but I was trying it out on the fiddle and when there are ticks, you can no longer click on the timeline bar and have the handle move to that point. However, clicking above the tick still works.

Also, is a table really the best option for displaying ticks?

**Comment by ValentinH** [comment]
Indeed the ticks should be under the bar that's why. I'll rebase it and fix it.

About the table, why not?

**Comment by adgoncal** [comment]
I just thought there may be a better approach because it is not tabular data. 
But it is simple and it works, so I guess it should be fine.

**Comment by ValentinH** [comment]
Actually, the trick with the table is that you don't need to specify each tick's position. Just give the total width and they will be equally spread.

**Comment by ValentinH** [comment]
@adgoncal rebased so now the ticks are under the bar.

**Comment by adgoncal** [comment]
Cool!

**Comment by ValentinH** [comment]
Actually, the limit with the current table method is that if you want to draw circle as ticks, it is not possible. Indeed, it's using td borders...

**Comment by ValentinH** [comment]
I have replaced the table method by a method with ul displayed with flex. Now you can use whatever you want for the ticks: even circles ;)

See http://jsfiddle.net/ngrq2kdm/

**Pull request merged**
