### PR TITLE
Support clicks on bar

### PR DESCRIPTION
**Pull request by ValentinH**
Add the possibility to directly click on the slider bar to set the value. It is also possible to click and drag directly from the bar.

Add a bar wrapper to enlarge the clickable area.

### CODE REVIEW

**Comment by psalaberria002** [comment]
+1 Nice feature.

**Comment by mcrumm** [comment]
+1 This would be super helpful.

**Comment by antoescu** [comment]
+ 1 It is needed

**Comment by radek-anuszewski** [comment]
I checked pull request submitted by @ValentinH on latest Chrome and on Motorola Moto G II with Android 5.0 (by Phonegap Developer app) and everything works well, I think it is worth merge.

**Pull request merged**
