### PR TITLE
Remove unnecessary dependency

### PR DESCRIPTION
**Pull request by a-tarasyuk**
After release 0.1.31 appeared error

Uncaught Error: Cannot find module "underscore"

### CODE REVIEW

**Comment by ValentinH** [comment]
You are right. I don't know why @e-cloud added it... Maybe because of the throttle function but @rzajac added it in the code base to remove the underscore dependency.

**Comment by a-tarasyuk** [comment]
@ValentinH could you update version from 0.1.31 to 0.1.32 ?

**Comment by ValentinH** [comment]
it's done. Tell me if it's ok for you please ;)

**Comment by a-tarasyuk** [comment]
For me works fine. Thank you very much.

**Comment by e-cloud** [comment]
@a-tarasyuk , i'm so sorry, in my local dev, i tried to use underscore to do some other thing. And afterward i gave it up. but the code's clean-up wat not thorough.

**Pull request merged**
