### PR TITLE
Updated to work with jqLite/Ionic

### PR DESCRIPTION
**Pull request by willyboy**
Bound touchmove/mousemove to slider instead of document. Used $document.one to remove event on touchend/mouseup

### CODE REVIEW

**Comment by leandroz** [comment]
merge?

**Comment by Yuripetusko** [comment]
+1 for the merge

**Comment by Yuripetusko** [comment]
the only thing is missing here is bower main files are not properly defined. So my gulp wiredep cannot pick correct files to inject in html

it should be something like:

    "main": [
        "rzslider.js",
        "dist/rzslider.min.css"
    ],

**Comment by Yuripetusko** [comment]
I doesn't look like you merged it properly? For example I cannot see `this.sliderElem.on('touchmove',` code in your master now

**Comment by rzajac** [comment]
Unfortunately I had to go back to binding events to $document due to some problems - but I forgot to document it in the commit :(

It happened here: 3772b558af8bfe5f50ae0e8978c12b3487b83303

**Comment by Yuripetusko** [comment]
Ok. Well it doesn't work with Ionic this way :/

**Comment by Yuripetusko** [comment]
maybe @willyboy can help out.?

**Comment by willyboy** [comment]
I'll take a look tonight. @rzajac Any specific problems I might be able to address in a fix?

**Comment by rzajac** [comment]
If we could find a way for it to work in Ionic that would be great. I don't use it so I have no way to test it.

**Pull request merged**
